[project]
name = "mos-med-data-gap-analyzer"
version = "0.1.0"
description = "MosMedData Gap Analyzer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "pydicom>=3.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
